[workspace]
resolver = "3"
members = [ "multiple-area-calculator", "parser-u32","rect-area", "the-gatekeeper", "the-geometric-shapes-calculator", "the-functional-surveyor", "the-safe-divider", "the-structured-surveyor", "words-counter"]
